# Generated by Django 3.2.2 on 2021-05-16 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('blood_type', models.CharField(max_length=5)),
                ('hospital_name', models.CharField(default='DMH', max_length=50)),
                ('visit_type', models.CharField(default='Consult', max_length=50)),
                ('last_interaction', models.DateField(default=datetime.datetime(2021, 5, 16, 17, 33, 31, 75821))),
            ],
        ),
    ]
