# Generated by Django 3.2.2 on 2021-05-16 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hospital_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_interaction',
            field=models.DateField(default=datetime.datetime(2021, 5, 16, 17, 46, 8, 817918)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='visit_type',
            field=models.CharField(max_length=50),
        ),
    ]
