# Generated by Django 3.2.2 on 2021-05-16 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0002_auto_20210516_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_interaction',
            field=models.DateField(default=datetime.datetime(2021, 5, 17, 0, 36, 24, 285834)),
        ),
    ]
