# Generated by Django 3.2.2 on 2021-05-17 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0003_alter_patient_last_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_interaction',
            field=models.DateField(default=datetime.datetime(2021, 5, 17, 13, 1, 58, 282686)),
        ),
    ]
