# Generated by Django 3.2.2 on 2021-05-18 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0004_alter_patient_last_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth_place',
            field=models.CharField(default='Pune', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.CharField(default=datetime.datetime(2021, 5, 18, 19, 5, 15, 835108), max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Male', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(default='Maharashtra', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(default='Default address', max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(default='b +ve', max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital_name',
            field=models.CharField(default='DMH', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_interaction',
            field=models.DateField(default=datetime.datetime(2021, 5, 18, 19, 5, 15, 835323)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='visit_type',
            field=models.CharField(default='Consult', max_length=50),
        ),
    ]
