# Generated by Django 3.2.2 on 2021-06-27 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0007_auto_20210518_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.CharField(default=datetime.datetime(2021, 6, 28, 0, 24, 7, 426377), max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_interaction',
            field=models.DateField(default=datetime.datetime(2021, 6, 28, 0, 24, 7, 426377)),
        ),
    ]
